[package]
name = "skale"
version = "0.1.0"
edition = "2021"
authors = ["Rowan Lee"]
rust-version = "1.64.0"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
